"""Clean-room Orbweb protocol primitives used by Hubble Connected."""

from .authentication import (
    DEFAULT_AUTH_TIMEOUT,
    ORBWEB_AUTH_ACCOUNT,
    ORBWEB_AUTH_REMOTE_PORT,
    OrbwebAuthenticationError,
    async_authenticate_camera,
)
from .control import (
    RendezvousControlRejected,
    RendezvousControlResult,
    async_run_control_exchange,
)
from .crypto import (
    KeyExchange,
    derive_aes_key,
    derive_iv,
    pkcs7_pad,
    pkcs7_unpad,
)
from .direct import (
    MAX_DIRECT_SIGNAL_PAYLOAD,
    DirectAddressRegistrationRequest,
    DirectCandidate,
    DirectConnectionForward,
    DirectConnectionRequest,
    parse_direct_connection_forward,
)
from .direct_client import (
    DEFAULT_DIRECT_FORWARD_TIMEOUT,
    DEFAULT_DIRECT_REGISTRATION_TIMEOUT,
    DIRECT_RENDEZVOUS_PORT,
    DirectListenerPlan,
    DirectListenerSession,
    DirectRendezvousRejected,
    async_open_direct_listener,
)
from .direct_listeners import (
    DEFAULT_DIRECT_BIND_ATTEMPTS,
    MAX_DIRECT_LISTENER_PORT,
    MIN_DIRECT_LISTENER_PORT,
    AcceptedDirectConnection,
    DirectListenerPool,
    async_open_direct_listener_pool,
)
from .direct_race import (
    DEFAULT_DIRECT_RACE_TIMEOUT,
    async_race_direct_candidates,
)
from .direct_tunnel import (
    DEFAULT_TUNNEL_HANDSHAKE_TIMEOUT,
    OrbwebDirectTunnelListener,
    async_open_direct_tunnel_listener,
)
from .framing import (
    BasePacket,
    BasePacketBuffer,
    OrbwebCommand,
    OrbwebProtocolError,
    apply_body_mask,
    async_read_packet,
    async_write_packet,
    encode_packet,
)
from .handshake import (
    TunnelKeyMaterial,
    async_accept_tunnel_key,
    async_negotiate_tunnel_key,
)
from .identity import (
    OrbwebClientIdentity,
    build_client_id,
    generate_client_token,
    validate_client_token,
)
from .lan_client import (
    CONTROL_PORT,
    DEFAULT_CONTROL_CONNECT_TIMEOUT,
    DEFAULT_CONTROL_EXCHANGE_TIMEOUT,
    OrbwebControlCannotConnect,
    async_open_lan_rtsp_mapping,
)
from .nat import (
    NAT_PROBE_ACK_COMMANDS,
    NAT_PROBE_REQUEST_COMMANDS,
    NatInfoRequest,
    NatInfoResponse,
    NatProbeRequest,
    NatTypeQuery,
    build_nat_client_id,
    parse_nat_info_response,
)
from .nat_client import (
    DEFAULT_NAT_TIMEOUT,
    NAT_CONTROL_PORT,
    NAT_PROBE_PORTS,
    NatTraversalPlan,
    NatTraversalResult,
    async_detect_nat,
)
from .pool import (
    OrbwebLanMappingPool,
    OrbwebStablePort,
    async_source_ipv4_address,
)
from .port_mapping import (
    DEFAULT_KEEPALIVE_INITIAL_DELAY,
    DEFAULT_KEEPALIVE_INTERVAL,
    DEFAULT_REMOTE_RTSP_PORT,
    OrbwebPortMapping,
    async_open_port_mapping,
)
from .rendezvous import (
    DEFAULT_RENDEZVOUS_HOST,
    OrbwebRendezvousClient,
    OrbwebRendezvousError,
    RendezvousRequest,
    RendezvousServers,
    parse_rendezvous_response,
)
from .requests import (
    ClientRegistrationRequest,
    HostConnectionRequest,
    HostNicRequest,
)
from .responses import (
    HostNicResponse,
    ServerUtilityResponse,
    parse_host_nic_response,
    parse_server_utility_response,
)
from .shunt import (
    MAX_SHUNT_REGISTRATION_PAYLOAD,
    ShuntCandidate,
    ShuntRegistrationRequest,
    ShuntRegistrationResponse,
    parse_shunt_registration_response,
)
from .shunt_client import (
    DEFAULT_SHUNT_RETRY_INTERVAL,
    DEFAULT_SHUNT_TIMEOUT,
    SHUNT_PORT,
    ShuntRegistrationPlan,
    ShuntRegistrationRejected,
    async_register_with_shunt,
)
from .tunnel import (
    HEADER_LENGTH as TUNNEL_HEADER_LENGTH,
)
from .tunnel import (
    MappingAnnouncement,
    TunnelCipher,
    TunnelFrame,
    TunnelHeader,
    TunnelOperation,
    TunnelStreamRole,
    decode_tunnel_packet,
    encode_tunnel_packet,
)

__all__ = [
    "BasePacket",
    "BasePacketBuffer",
    "AcceptedDirectConnection",
    "ClientRegistrationRequest",
    "CONTROL_PORT",
    "DEFAULT_AUTH_TIMEOUT",
    "DEFAULT_CONTROL_CONNECT_TIMEOUT",
    "DEFAULT_CONTROL_EXCHANGE_TIMEOUT",
    "DEFAULT_DIRECT_FORWARD_TIMEOUT",
    "DEFAULT_DIRECT_REGISTRATION_TIMEOUT",
    "DEFAULT_DIRECT_RACE_TIMEOUT",
    "DEFAULT_TUNNEL_HANDSHAKE_TIMEOUT",
    "DEFAULT_DIRECT_BIND_ATTEMPTS",
    "DirectAddressRegistrationRequest",
    "DirectCandidate",
    "DirectConnectionForward",
    "DirectConnectionRequest",
    "DirectListenerPlan",
    "DirectListenerSession",
    "DirectListenerPool",
    "DirectRendezvousRejected",
    "DIRECT_RENDEZVOUS_PORT",
    "DEFAULT_RENDEZVOUS_HOST",
    "DEFAULT_SHUNT_RETRY_INTERVAL",
    "DEFAULT_SHUNT_TIMEOUT",
    "DEFAULT_NAT_TIMEOUT",
    "DEFAULT_KEEPALIVE_INITIAL_DELAY",
    "DEFAULT_KEEPALIVE_INTERVAL",
    "DEFAULT_REMOTE_RTSP_PORT",
    "HostConnectionRequest",
    "HostNicRequest",
    "HostNicResponse",
    "KeyExchange",
    "MAX_SHUNT_REGISTRATION_PAYLOAD",
    "MAX_DIRECT_SIGNAL_PAYLOAD",
    "MAX_DIRECT_LISTENER_PORT",
    "MIN_DIRECT_LISTENER_PORT",
    "MappingAnnouncement",
    "NAT_PROBE_ACK_COMMANDS",
    "NAT_PROBE_REQUEST_COMMANDS",
    "NAT_CONTROL_PORT",
    "NAT_PROBE_PORTS",
    "NatInfoRequest",
    "NatInfoResponse",
    "NatProbeRequest",
    "NatTypeQuery",
    "NatTraversalPlan",
    "NatTraversalResult",
    "OrbwebCommand",
    "OrbwebAuthenticationError",
    "OrbwebControlCannotConnect",
    "OrbwebDirectTunnelListener",
    "OrbwebLanMappingPool",
    "OrbwebStablePort",
    "OrbwebClientIdentity",
    "OrbwebPortMapping",
    "OrbwebProtocolError",
    "OrbwebRendezvousClient",
    "OrbwebRendezvousError",
    "ORBWEB_AUTH_ACCOUNT",
    "ORBWEB_AUTH_REMOTE_PORT",
    "RendezvousRequest",
    "RendezvousServers",
    "RendezvousControlRejected",
    "RendezvousControlResult",
    "ServerUtilityResponse",
    "SHUNT_PORT",
    "ShuntCandidate",
    "ShuntRegistrationRequest",
    "ShuntRegistrationResponse",
    "ShuntRegistrationPlan",
    "ShuntRegistrationRejected",
    "TunnelKeyMaterial",
    "TunnelCipher",
    "TunnelFrame",
    "TunnelHeader",
    "TunnelOperation",
    "TunnelStreamRole",
    "TUNNEL_HEADER_LENGTH",
    "apply_body_mask",
    "async_read_packet",
    "async_open_direct_listener",
    "async_open_direct_listener_pool",
    "async_open_direct_tunnel_listener",
    "async_open_lan_rtsp_mapping",
    "async_open_port_mapping",
    "async_source_ipv4_address",
    "async_race_direct_candidates",
    "async_register_with_shunt",
    "async_run_control_exchange",
    "async_negotiate_tunnel_key",
    "async_detect_nat",
    "async_accept_tunnel_key",
    "async_authenticate_camera",
    "async_write_packet",
    "build_client_id",
    "build_nat_client_id",
    "derive_aes_key",
    "derive_iv",
    "decode_tunnel_packet",
    "encode_packet",
    "encode_tunnel_packet",
    "generate_client_token",
    "pkcs7_pad",
    "pkcs7_unpad",
    "parse_rendezvous_response",
    "parse_direct_connection_forward",
    "parse_host_nic_response",
    "parse_nat_info_response",
    "parse_server_utility_response",
    "parse_shunt_registration_response",
    "validate_client_token",
]
